# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Frontend Build

on:
    push:
        paths: ["frontend/**"]
    pull_request:
        paths: ["frontend/**"]

jobs:
    build:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: frontend

        steps:
            - uses: actions/checkout@v4

            - name: Setup
              uses: N0tExisting/setup-pnpm@v1
              with:
                  node-version: 22.17.1
                  pnpm-version: 10.13.1
              continue-on-error: true

            - name: Install
              run: pnpm i --frozen-lockfile

            - name: Build
              run: pnpm run build

            - name: Upload
              uses: actions/upload-artifact@v4
              with:
                  name: "frontend_dist"
                  path: "frontend/dist"
                  retention-days: 1
